export const keyWordBarcodeData = {
  tela: { name: "tela", code: "T", startIndex: 0, finalIndex: 1 },
  espuma: { name: "espuma", code: "E", startIndex: 0, finalIndex: 1 },
  bondeo: { name: "bondeo", code: "B", startIndex: 0, finalIndex: 1 },
  cortecuadros: {
    name: "cortecuadros",
    code: "11",
    startIndex: 4,
    finalIndex: 6,
  },
  prehormarcopas: {
    name: "prehormarcopas",
    code: "21",
    startIndex: 4,
    finalIndex: 6,
  },
  cortecopas: {
    name: "cortecopas",
    code: "31",
    startIndex: 4,
    finalIndex: 6,
  },
  revisarcopas: {
    name: "revisarcopas",
    code: "41",
    startIndex: 4,
    finalIndex: 6,
  },
  prehormartapabocas: {
    name: "prehormartapabocas",
    code: "21",
    startIndex: 4,
    finalIndex: 6,
  },
  troquelado: {
    name: "troquelado",
    code: "31",
    startIndex: 4,
    finalIndex: 6,
  },
  presilla: { name: "presilla", code: "41", startIndex: 4, finalIndex: 6 },
  platina: { name: "platina", code: "42", startIndex: 4, finalIndex: 6 },
  ozono: { name: "ozono", code: "43", startIndex: 4, finalIndex: 6 },
  empaquebolsa: {
    name: "empaquebolsa",
    code: "44",
    startIndex: 4,
    finalIndex: 6,
  },
  empaquecaja: {
    name: "empaquecaja",
    code: "46",
    startIndex: 4,
    finalIndex: 6,
  },
  sublimado: { name: "sublimado", code: "17", startIndex: 4, finalIndex: 6 },
};
